AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Cluster and Fargate Pod Role'

Resources:

  # EKS Cluster Role
  EksClusterRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: "eks.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
      Tags:
        - Key: "Name"
          Value: "eks-cluster-role"

  # EKS Fargate Pod Role
  EksFargatePodRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: "eks-fargate-pods.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess"
        - "arn:aws:iam::aws:policy/AWSCertificateManagerFullAccess"  # Certificate Manager: Full Access
        - "arn:aws:iam::aws:policy/AWSResourceGroupsTaggingAPIReadOnlyAccess"  # Resource Group Tagging: Limited Read
        - "arn:aws:iam::aws:policy/AmazonRoute53FullAccess"  # Route 53 Full Management
      Tags:
        - Key: "Name"
          Value: "eks-fargate-pod-role"

Outputs:
  EksClusterRoleArn:
    Description: The ARN of the EKS Cluster Role
    Value: !GetAtt EksClusterRole.Arn

  EksFargatePodRoleArn:
    Description: The ARN of the EKS Fargate Pod Role
    Value: !GetAtt EksFargatePodRole.Arn
