apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-api
          image: 992382688515.dkr.ecr.ap-southeast-1.amazonaws.com/todo-auth:latest
          env:
            - name: TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TOKEN_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"