version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - ':3000'  # Expose only on internal network (no public ports)
    environment:
      TOKEN_KEY: 'very_secure_token'
    networks:
      - internal

  users:
    build: ./users-api
    ports:
      - '8080:3000'
    environment:
      MONGODB_CONNECTION_URI: ${MONGODB_CONNECTION_URI}
      AUTH_API_ADDRESS: 'auth:3000'
      LOGS_DIR: 'user-logs'
    volumes:
      - app-logs:/app/app-logs
    networks:
      - public
      - internal  # Users service needs access to auth service

  tasks:
    build: ./tasks-api
    ports:
      - '4000:3000'
    environment:
      MONGODB_CONNECTION_URI: ${MONGODB_CONNECTION_URI}
      AUTH_API_ADDRESS: 'auth:3000'
      LOGS_DIR: 'tasks-logs'
    volumes:
      - app-logs:/app/app-logs
    networks:
      - public
      - internal  # Tasks service also needs access to auth service

  frontend:
    build: ./frontend
    ports:
      - '80:80'
    networks:
      - public

volumes:
  app-logs:

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
