apiVersion: v1
kind: Service
metadata:
  name: tasks-service
  labels:
    app: task
spec:
  type: NodePort
  selector:
    app: task
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP